// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_Test_1)
QT_DECLARE_EXTERN_RESOURCE(qmake_Test_1)
QT_DECLARE_EXTERN_RESOURCE(Test_1_raw_qml_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_Test_1)

class Test_1Plugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    Test_1Plugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_Test_1)
QT_KEEP_RESOURCE(qmlcache_Test_1)
QT_KEEP_RESOURCE(qmake_Test_1)
QT_KEEP_RESOURCE(Test_1_raw_qml_0)
    }
};



#include "Test_1plugin_Test_1Plugin.moc"
